# Generated by Django 5.1 on 2024-09-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'aboutbox',
                'verbose_name_plural': 'aboutboxes',
                'db_table': 'web_aboutbox',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'gallerycategory',
                'verbose_name_plural': 'gallerycategories',
                'db_table': 'web_gallerycategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Galleryimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'galleryimage',
                'verbose_name_plural': 'galleryimages',
                'db_table': 'web_galleryimage',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Legacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'legacy',
                'verbose_name_plural': 'legacies',
                'db_table': 'web_legacy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
            ],
            options={
                'verbose_name': 'productcategory',
                'verbose_name_plural': 'productcategories',
                'db_table': 'web_productcategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'productfeature',
                'verbose_name_plural': 'productfeatures',
                'db_table': 'web_productfeature',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='slider')),
                ('brandlogo', models.ImageField(upload_to='slider')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.productcategory')),
                ('features', models.ManyToManyField(to='web.productfeature')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'web_product',
                'ordering': ['-id'],
            },
        ),
    ]
