# Generated by Django 5.1 on 2024-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_aboutbox_gallerycategory_galleryimage_legacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-id'], 'verbose_name': 'productcategory', 'verbose_name_plural': 'productcategorie'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
