# Generated by Django 5.1 on 2024-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
