# Generated by Django 5.1 on 2024-09-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_productcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.gallerycategory'),
        ),
    ]
